[project]
name = ""
version = ""
description = ""
authors = [
    {name = "",email = "vgol@double.cloud"},
]
dependencies = [
    "pytest>=7.4.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

