# .github/workflows/app.yaml
name: PyTest
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    run_mypy:
      type: boolean
      default: false
      description: "Check to run mypy"

jobs:
  test:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install pdm pytest
      - run: pwd
      - run: ls -laht
      - name: Run test suite 1
        if: always()
        run: |
          pytest super_app/super_app_tests/test_one.py  --junitxml=./report-1.xml
      - name: Run test suite 2
        if: always()
        run: |
          pytest super_app/super_app_tests/sub  --junitxml=./report-2.xml
      #     evilkost/publish-unit-test-result-action
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        #uses: evilkost/publish-unit-test-result-action@6d2338823691ac5cdd10c76b1e8c7a12da852cf7
        if: always()
        with:
          files: |
            ./report-*.xml


