# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install pdm pytest
      - name: Run test suite
        run: |
          pytest .  --junitxml=./report.xml
      #     evilkost/publish-unit-test-result-action
      - name: Publish Test Results
        uses: evilkost/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./report.xml


