# .github/workflows/app.yaml
name: PyTest2
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    run_mypy:
      type: boolean
      default: false
      description: "Check to run mypy"

jobs:
  test:
    timeout-minutes: 10
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    container:
      image: python:3.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
#      # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install pytest
      - run: pwd
      - run: ls -laht
      - name: Run test suite 1
        if: always()
        run: |
          pytest super_app/super_app_tests/test_one.py  --junitxml=./report/report-1.xml
          
      - uses: actions/upload-artifact@v3
        with:
          name: pytest_reports
          path: ./report/

  test2:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    container:
      image: python:3.10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

#      # Setup Python (faster than using Python container)
#      - name: Setup Python
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install pytest
      - run: pwd
      - run: ls -laht
      - name: Run test suite 2
        if: always()
        run: |
          pytest super_app/super_app_tests/sub  --junitxml=./report/report-2.xml
          

      - uses: actions/upload-artifact@v3
        with:
          name: pytest_reports
          path: ./report/

  publish_results:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, linux]
    needs: [ "test", "test2"]
    if: always()
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
#    container:
#      image: ubuntu:22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pytest_reports
          path: ./report/
      - run: ls -laht report

      - name: Publish Test Results
        uses: datalens-tech/publish-unit-test-result-action@sha256:eb70f771279757a7448a3fbaf4d3b24436cd9c81
        with:
          files: |
            ./report/*.xml


#      - name: Publish Test Results
#        uses: evilkost/publish-unit-test-result-action@6d2338823691ac5cdd10c76b1e8c7a12da852cf7
#        if: always()
#        with:
#          files: |
#            ./report/*.xml


