# .github/workflows/app.yaml
name: PyTest
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    run_mypy:
      type: boolean
      default: false
      description: "Check to run mypy"

jobs:
  test:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install pdm pytest
      - name: Run test suite
        run: |
          pytest .  --junitxml=./report.xml
      #     evilkost/publish-unit-test-result-action
      - name: Publish Test Results

        uses: evilkost/publish-unit-test-result-action@f0b5d2433f350eff587831d4ad22cb15aab75866
        if: always()
        with:
          files: |
            ./report.xml


